---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
## Notes ...
# 2015-10-16
# (1) 11:38 Initial commit to check git hub

## Loading and preprocessing the datat

```{r, echo = TRUE}
activity <- read.table(unz("activity.zip", "activity.csv"), header=T, quote="\"", sep=",")
dim(activity)
str(activity)
```


## What is mean total number of steps taken per day?
```{r, echo = TRUE}
library(dplyr)
day_steps <- group_by (activity, date)
date_daysum <- summarize(day_steps, daysum = sum(steps))
ds1 <- matrix( select(date_daysum, daysum)  )
steps_per_day <- ds1[[1]]
hist(steps_per_day, breaks = seq(0,22000,250), xlim = c(0,25000) )

mean_steps_per_day <- mean(ds1[[1]], na.rm = T)
print ( paste("Mean Steps per Day = ", mean_steps_per_day) )

median_steps_per_day <- median(ds1[[1]], na.rm = T)
print ( paste("Median Steps per Day = ", median_steps_per_day) )

```

## What is the average daily activity pattern?
```{r, echo=T}
df.int5 <- summarize(group_by(activity, interval), step_5min_mean = mean(steps, na.rm=T))
par(xaxs='i')
plot(df.int5, type = 'l', xlim=c(0,2500))
print ( df.int5[df.int5$step_5min_mean ==  max(df.int5$step_5min_mean),] )
print ( filter(df.int5, step_5min_mean == max(step_5min_mean)) )
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
